baseURL: 'http://hqapps.tk/'
languageCode: 'en-us'
title: 'HQ Apps'

theme: "hq-hugo-theme"

markup:
  goldmark:
    renderer:
      unsafe: true
      
outputFormats:
  downloads:
    baseName: dl
    isPlainText: true
    mediaType: text/html
    path: dl
